In [1]:
# IMPORTAÇÕES
import pandas as pd
import numpy as np

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [7]:
# CARREGAMENTO DOS DADOS

path = '/content/drive/MyDrive/KPMG_VI_New_raw_data_update_final.xlsx'

# Verificar as planilhas disponíveis
excel = pd.ExcelFile(arquivo)
print(excel.sheet_names)

# Carregar a planilha Transactions
df = pd.read_excel(
    arquivo,
    sheet_name='Transactions'
)

display(df.head())
print("Dimensões:", df.shape)

['Title Sheet', 'Transactions', 'NewCustomerList', 'CustomerDemographic', 'CustomerAddress']

,Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
1,1,2,2950,2017-02-25 00:00:00,False,Approved,Solex,Standard,medium,medium,71.49,53.62,41245
2,2,3,3120,2017-05-21 00:00:00,True,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,41701
3,3,37,402,2017-10-16 00:00:00,False,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,36361
4,4,88,3135,2017-08-31 00:00:00,False,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.1,36145

Dimensões: (20001, 13)

In [8]:
# CARREGAMENTO DOS DADOS

arquivo = '/content/drive/MyDrive/KPMG_VI_New_raw_data_update_final.xlsx'

# Verificar as planilhas disponíveis
excel = pd.ExcelFile(arquivo)
print(excel.sheet_names)

# Carregar a planilha Transactions
df = pd.read_excel(
    arquivo,
    sheet_name='Transactions'
)

display(df.head())
print("Dimensões:", df.shape)

['Title Sheet', 'Transactions', 'NewCustomerList', 'CustomerDemographic', 'CustomerAddress']

,Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
1,1,2,2950,2017-02-25 00:00:00,False,Approved,Solex,Standard,medium,medium,71.49,53.62,41245
2,2,3,3120,2017-05-21 00:00:00,True,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,41701
3,3,37,402,2017-10-16 00:00:00,False,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,36361
4,4,88,3135,2017-08-31 00:00:00,False,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.1,36145

Dimensões: (20001, 13)

In [9]:
# CONFERÊNCIA DO CABEÇALHO E DOS TIPOS

print("Nomes das colunas:")
print(df.columns.tolist())

print("\nTipos de dados:")
print(df.dtypes)

print("\nPrimeiras linhas:")
display(df.head())

print("\nQuantidade de linhas e colunas:")
print(df.shape)

Nomes das colunas:
['Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only. ', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']

Tipos de dados:
Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only.     object
Unnamed: 1                                                                                                                                                                       object
Unnamed: 2                                                                                                                                                                       object
Unnamed: 3                                                                                                                                                                       object
Unnamed: 4                                                                                                                                                                       object
Unnamed: 5                                                                                                                                                                       object
Unnamed: 6                                                                                                                                                                       object
Unnamed: 7                                                                                                                                                                       object
Unnamed: 8                                                                                                                                                                       object
Unnamed: 9                                                                                                                                                                       object
Unnamed: 10                                                                                                                                                                      object
Unnamed: 11                                                                                                                                                                      object
Unnamed: 12                                                                                                                                                                      object
dtype: object

Primeiras linhas:

,Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only.,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
1,1,2,2950,2017-02-25 00:00:00,False,Approved,Solex,Standard,medium,medium,71.49,53.62,41245
2,2,3,3120,2017-05-21 00:00:00,True,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,41701
3,3,37,402,2017-10-16 00:00:00,False,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,36361
4,4,88,3135,2017-08-31 00:00:00,False,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.1,36145

Quantidade de linhas e colunas:
(20001, 13)

In [10]:
# DUPLICATAS EXATAS

duplicatas_exatas = df.duplicated()

print("Quantidade de duplicatas exatas:",
      duplicatas_exatas.sum())

# Visualizar as duplicatas encontradas
display(df[duplicatas_exatas])

Quantidade de duplicatas exatas: 0

Empty DataFrame
Columns: [Note: The data and information in this document is reflective of a hypothetical situation and client. This document is to be used for KPMG Virtual Internship purposes only. , Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Unnamed: 6, Unnamed: 7, Unnamed: 8, Unnamed: 9, Unnamed: 10, Unnamed: 11, Unnamed: 12]
Index: []

In [11]:
# DUPLICATAS POR SUBCONJUNTO DE COLUNAS

if 'transaction_id' in df.columns:

    duplicatas_id = df.duplicated(
        subset=['transaction_id'],
        keep=False
    )

    print("Registros com transaction_id repetido:",
          duplicatas_id.sum())

    display(
        df.loc[duplicatas_id].sort_values('transaction_id')
    )

else:
    print("A coluna transaction_id não foi encontrada.")

# Transaction_id deve identificar uma transação individual. Se houver repetições, precisamos investigar se são erros de registro ou alguma particularidade da base antes de remover linhas.

A coluna transaction_id não foi encontrada.

In [16]:
# UNICIDADE DOS IDENTIFICADORES

for coluna in ['transaction_id', 'customer_id', 'product_id']:
    if coluna in df.columns:
        print(f"\nColuna: {coluna}")
        print("Valores únicos:", df[coluna].nunique())
        print("Valores ausentes:", df[coluna].isna().sum())
        print("Valores repetidos:",
              df[coluna].duplicated().sum())

In [15]:
# ESTRATÉGIA DE TRATAMENTO E IMPACTO

df_limpo = df.copy()

# Indicador antes da limpeza
if 'list_price' in df.columns:
    faturamento_antes = df['list_price'].sum()

# Remover somente linhas completamente duplicadas
quantidade_antes = len(df_limpo)

df_limpo = df_limpo.drop_duplicates()

quantidade_deletada = quantidade_antes - len(df_limpo)

print("Linhas antes:", quantidade_antes)
print("Linhas depois:", len(df_limpo))
print("Duplicatas removidas:", quantidade_deletada)

# Comparar o indicador
if 'list_price' in df.columns:
    faturamento_depois = df_limpo['list_price'].sum()

    print("\nSoma de list_price antes:", faturamento_antes)
    print("Soma de list_price depois:", faturamento_depois)
    print("Diferença:", faturamento_antes - faturamento_depois)

Linhas antes: 20001
Linhas depois: 20001
Duplicatas removidas: 0

In [ ]:
# 1. Se o resultado de duplicatas exatas for zero, isso garante que não há registros repetidos? Por quê?

# Não. Podem existir registros que representam a mesma transação, mas possuem alguma diferença em uma coluna, como uma data, um preço ou um texto. Por isso, também precisamos verificar duplicatas usando identificadores ou subconjuntos de colunas.

# 2. Em uma base de transações, duas linhas idênticas são sempre um erro? Dê um exemplo em que não seriam.

# Não necessariamente. Em uma situação de vendas, dois produtos iguais podem ser vendidos pelo mesmo preço, para o mesmo cliente e na mesma data. Se cada linha representar uma unidade ou uma venda legítima independente, os registros podem ser iguais sem serem erros.

# 3. Por que a escolha das colunas que definem "o mesmo registro" é uma decisão de negócio, e não apenas técnica? Relacione com a etapa de Entendimento do Negócio do CRISP-DM.

# Porque é necessário compreender o significado de cada registro e as regras da empresa. Na etapa de Entendimento do Negócio do CRISP-DM, definimos o que caracteriza uma transação única. Uma escolha incorreta pode excluir vendas legítimas ou contar a mesma venda mais de uma vez.